// category: "gym" | "elite4" | "champion" | "rival" | "villain"
// teams use PokeAPI-compatible names (lowercase, hyphenated)

const GYM_DATA = {
  1: {
    name:"Generation I", region:"Kanto",
    games:[{id:"frlg",name:"FireRed / LeafGreen"},{id:"rby",name:"Red / Blue / Yellow"}],
    opponents:{
      frlg:[
        // --- Gym Leaders ---
        {id:"brock",     name:"Brock",     role:"Gym Leader #1",   badge:"Boulder Badge",  specialType:"rock",     category:"gym",
          team:[{name:"geodude",level:12},{name:"onix",level:14}]},
        {id:"misty",     name:"Misty",     role:"Gym Leader #2",   badge:"Cascade Badge",  specialType:"water",    category:"gym",
          team:[{name:"staryu",level:18},{name:"starmie",level:21}]},
        {id:"lt-surge",  name:"Lt. Surge", role:"Gym Leader #3",   badge:"Thunder Badge",  specialType:"electric", category:"gym",
          team:[{name:"voltorb",level:21},{name:"pikachu",level:18},{name:"raichu",level:24}]},
        {id:"erika",     name:"Erika",     role:"Gym Leader #4",   badge:"Rainbow Badge",  specialType:"grass",    category:"gym",
          team:[{name:"victreebel",level:29},{name:"tangela",level:24},{name:"vileplume",level:29}]},
        {id:"koga",      name:"Koga",      role:"Gym Leader #5",   badge:"Soul Badge",     specialType:"poison",   category:"gym",
          team:[{name:"koffing",level:37},{name:"muk",level:39},{name:"koffing",level:37},{name:"weezing",level:43}]},
        {id:"sabrina",   name:"Sabrina",   role:"Gym Leader #6",   badge:"Marsh Badge",    specialType:"psychic",  category:"gym",
          team:[{name:"kadabra",level:38},{name:"mr-mime",level:37},{name:"venomoth",level:38},{name:"alakazam",level:43}]},
        {id:"blaine",    name:"Blaine",    role:"Gym Leader #7",   badge:"Volcano Badge",  specialType:"fire",     category:"gym",
          team:[{name:"growlithe",level:42},{name:"ponyta",level:40},{name:"rapidash",level:42},{name:"arcanine",level:47}]},
        {id:"giovanni",  name:"Giovanni",  role:"Gym Leader #8",   badge:"Earth Badge",    specialType:"ground",   category:"gym",
          team:[{name:"rhyhorn",level:45},{name:"dugtrio",level:42},{name:"nidoqueen",level:44},{name:"nidoking",level:45},{name:"rhyhorn",level:50}]},
        // --- Elite Four ---
        {id:"lorelei",   name:"Lorelei",   role:"Elite Four #1",   badge:null,             specialType:"ice",      category:"elite4",
          team:[{name:"dewgong",level:54},{name:"cloyster",level:53},{name:"slowbro",level:54},{name:"jynx",level:56},{name:"lapras",level:60}]},
        {id:"bruno",     name:"Bruno",     role:"Elite Four #2",   badge:null,             specialType:"fighting", category:"elite4",
          team:[{name:"onix",level:53},{name:"hitmonchan",level:55},{name:"hitmonlee",level:55},{name:"onix",level:56},{name:"machamp",level:58}]},
        {id:"agatha",    name:"Agatha",    role:"Elite Four #3",   badge:null,             specialType:"ghost",    category:"elite4",
          team:[{name:"gengar",level:54},{name:"haunter",level:54},{name:"gengar",level:58},{name:"arbok",level:58},{name:"gengar",level:60}]},
        {id:"lance1",    name:"Lance",     role:"Elite Four #4",   badge:null,             specialType:"dragon",   category:"elite4",
          team:[{name:"gyarados",level:56},{name:"dragonair",level:54},{name:"dragonair",level:54},{name:"aerodactyl",level:58},{name:"dragonite",level:60}]},
        // --- Champion ---
        {id:"blue-champ",name:"Blue",      role:"Champion",        badge:null,             specialType:"mixed",    category:"champion",
          team:[{name:"pidgeot",level:59},{name:"alakazam",level:59},{name:"rhydon",level:61},{name:"gyarados",level:61},{name:"arcanine",level:61},{name:"venusaur",level:65}]},
        // --- Rivals ---
        {id:"blue-r1",   name:"Blue",      role:"Rival — Route 22 (early)",  badge:null,  specialType:"mixed",    category:"rival",
          team:[{name:"pidgey",level:9},{name:"charmander",level:9}]},
        {id:"blue-r2",   name:"Blue",      role:"Rival — Silph Co.",          badge:null,  specialType:"mixed",    category:"rival",
          team:[{name:"pidgeot",level:37},{name:"growlithe",level:35},{name:"alakazam",level:38},{name:"gyarados",level:38},{name:"venusaur",level:40}]},
        // --- Villains ---
        {id:"giovanni-silph", name:"Giovanni", role:"Team Rocket — Silph Co.", badge:null, specialType:"ground",  category:"villain",
          team:[{name:"nidorino",level:37},{name:"rhyhorn",level:37},{name:"kangaskhan",level:35},{name:"nidoqueen",level:41}]},
      ],
      rby:[
        {id:"brock-rby",    name:"Brock",    role:"Gym Leader #1",  badge:"Boulder Badge",  specialType:"rock",     category:"gym",
          team:[{name:"geodude",level:10},{name:"onix",level:12}]},
        {id:"misty-rby",    name:"Misty",    role:"Gym Leader #2",  badge:"Cascade Badge",  specialType:"water",    category:"gym",
          team:[{name:"staryu",level:18},{name:"starmie",level:21}]},
        {id:"ltsurge-rby",  name:"Lt. Surge",role:"Gym Leader #3",  badge:"Thunder Badge",  specialType:"electric", category:"gym",
          team:[{name:"voltorb",level:21},{name:"pikachu",level:18},{name:"raichu",level:24}]},
        {id:"erika-rby",    name:"Erika",    role:"Gym Leader #4",  badge:"Rainbow Badge",  specialType:"grass",    category:"gym",
          team:[{name:"victreebel",level:29},{name:"tangela",level:24},{name:"vileplume",level:29}]},
        {id:"koga-rby",     name:"Koga",     role:"Gym Leader #5",  badge:"Soul Badge",     specialType:"poison",   category:"gym",
          team:[{name:"koffing",level:37},{name:"muk",level:39},{name:"koffing",level:37},{name:"weezing",level:43}]},
        {id:"sabrina-rby",  name:"Sabrina",  role:"Gym Leader #6",  badge:"Marsh Badge",    specialType:"psychic",  category:"gym",
          team:[{name:"kadabra",level:38},{name:"mr-mime",level:37},{name:"venomoth",level:38},{name:"alakazam",level:43}]},
        {id:"blaine-rby",   name:"Blaine",   role:"Gym Leader #7",  badge:"Volcano Badge",  specialType:"fire",     category:"gym",
          team:[{name:"growlithe",level:42},{name:"ponyta",level:40},{name:"rapidash",level:42},{name:"arcanine",level:47}]},
        {id:"giovanni-rby", name:"Giovanni", role:"Gym Leader #8",  badge:"Earth Badge",    specialType:"ground",   category:"gym",
          team:[{name:"rhyhorn",level:45},{name:"dugtrio",level:42},{name:"nidoqueen",level:44},{name:"nidoking",level:45},{name:"rhyhorn",level:50}]},
        {id:"lorelei-rby",  name:"Lorelei",  role:"Elite Four #1",  badge:null,             specialType:"ice",      category:"elite4",
          team:[{name:"dewgong",level:54},{name:"cloyster",level:53},{name:"slowbro",level:54},{name:"jynx",level:56},{name:"lapras",level:60}]},
        {id:"bruno-rby",    name:"Bruno",    role:"Elite Four #2",  badge:null,             specialType:"fighting", category:"elite4",
          team:[{name:"onix",level:53},{name:"hitmonchan",level:55},{name:"hitmonlee",level:55},{name:"onix",level:56},{name:"machamp",level:58}]},
        {id:"agatha-rby",   name:"Agatha",   role:"Elite Four #3",  badge:null,             specialType:"ghost",    category:"elite4",
          team:[{name:"gengar",level:54},{name:"haunter",level:54},{name:"gengar",level:58},{name:"arbok",level:58},{name:"gengar",level:60}]},
        {id:"lance-rby",    name:"Lance",    role:"Elite Four #4",  badge:null,             specialType:"dragon",   category:"elite4",
          team:[{name:"gyarados",level:56},{name:"dragonair",level:54},{name:"dragonair",level:54},{name:"aerodactyl",level:58},{name:"dragonite",level:60}]},
        {id:"blue-champ-rby",name:"Blue",   role:"Champion",       badge:null,             specialType:"mixed",    category:"champion",
          team:[{name:"pidgeot",level:59},{name:"alakazam",level:59},{name:"rhydon",level:61},{name:"gyarados",level:61},{name:"arcanine",level:61},{name:"venusaur",level:65}]},
        {id:"blue-r1-rby",  name:"Blue",    role:"Rival — Route 22 (early)", badge:null,   specialType:"mixed",    category:"rival",
          team:[{name:"pidgey",level:9},{name:"charmander",level:9}]},
        {id:"blue-r2-rby",  name:"Blue",    role:"Rival — Silph Co.",         badge:null,  specialType:"mixed",    category:"rival",
          team:[{name:"pidgeot",level:37},{name:"growlithe",level:35},{name:"alakazam",level:38},{name:"gyarados",level:38},{name:"venusaur",level:40}]},
        {id:"giovanni-silph-rby",name:"Giovanni",role:"Team Rocket — Silph Co.", badge:null,specialType:"ground",  category:"villain",
          team:[{name:"nidorino",level:37},{name:"rhyhorn",level:37},{name:"kangaskhan",level:35},{name:"nidoqueen",level:41}]},
      ]
    }
  },

  2: {
    name:"Generation II", region:"Johto",
    games:[{id:"hgss",name:"HeartGold / SoulSilver"},{id:"gsc",name:"Gold / Silver / Crystal"}],
    opponents:{
      hgss:[
        {id:"falkner",   name:"Falkner",   role:"Gym Leader #1",  badge:"Zephyr Badge",   specialType:"flying",   category:"gym",
          team:[{name:"pidgey",level:7},{name:"pidgeotto",level:9}]},
        {id:"bugsy",     name:"Bugsy",     role:"Gym Leader #2",  badge:"Hive Badge",     specialType:"bug",      category:"gym",
          team:[{name:"metapod",level:14},{name:"kakuna",level:14},{name:"scyther",level:16}]},
        {id:"whitney",   name:"Whitney",   role:"Gym Leader #3",  badge:"Plain Badge",    specialType:"normal",   category:"gym",
          team:[{name:"clefairy",level:17},{name:"miltank",level:19}]},
        {id:"morty",     name:"Morty",     role:"Gym Leader #4",  badge:"Fog Badge",      specialType:"ghost",    category:"gym",
          team:[{name:"gastly",level:21},{name:"haunter",level:21},{name:"haunter",level:23},{name:"gengar",level:25}]},
        {id:"chuck",     name:"Chuck",     role:"Gym Leader #5",  badge:"Storm Badge",    specialType:"fighting", category:"gym",
          team:[{name:"primeape",level:27},{name:"poliwrath",level:30}]},
        {id:"jasmine",   name:"Jasmine",   role:"Gym Leader #6",  badge:"Mineral Badge",  specialType:"steel",    category:"gym",
          team:[{name:"magnemite",level:30},{name:"magnemite",level:30},{name:"steelix",level:35}]},
        {id:"pryce",     name:"Pryce",     role:"Gym Leader #7",  badge:"Glacier Badge",  specialType:"ice",      category:"gym",
          team:[{name:"seel",level:27},{name:"dewgong",level:29},{name:"piloswine",level:31}]},
        {id:"clair",     name:"Clair",     role:"Gym Leader #8",  badge:"Rising Badge",   specialType:"dragon",   category:"gym",
          team:[{name:"dragonair",level:37},{name:"dragonair",level:37},{name:"dragonair",level:37},{name:"kingdra",level:40}]},
        {id:"will",      name:"Will",      role:"Elite Four #1",  badge:null,             specialType:"psychic",  category:"elite4",
          team:[{name:"xatu",level:40},{name:"jynx",level:41},{name:"slowbro",level:41},{name:"exeggutor",level:41},{name:"xatu",level:42}]},
        {id:"koga2",     name:"Koga",      role:"Elite Four #2",  badge:null,             specialType:"poison",   category:"elite4",
          team:[{name:"ariados",level:40},{name:"venomoth",level:41},{name:"forretress",level:43},{name:"muk",level:42},{name:"crobat",level:44}]},
        {id:"bruno2",    name:"Bruno",     role:"Elite Four #3",  badge:null,             specialType:"fighting", category:"elite4",
          team:[{name:"hitmontop",level:42},{name:"hitmonlee",level:42},{name:"hitmonchan",level:42},{name:"onix",level:43},{name:"machamp",level:46}]},
        {id:"karen",     name:"Karen",     role:"Elite Four #4",  badge:null,             specialType:"dark",     category:"elite4",
          team:[{name:"umbreon",level:42},{name:"vileplume",level:42},{name:"gengar",level:45},{name:"murkrow",level:44},{name:"houndoom",level:47}]},
        {id:"lance2",    name:"Lance",     role:"Champion",       badge:null,             specialType:"dragon",   category:"champion",
          team:[{name:"gyarados",level:44},{name:"dragonite",level:47},{name:"dragonite",level:47},{name:"aerodactyl",level:46},{name:"charizard",level:46},{name:"dragonite",level:50}]},
        // Rivals
        {id:"silver-r1", name:"Silver",    role:"Rival — Violet City",        badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"gastly",level:12},{name:"cyndaquil",level:14}]},
        {id:"silver-r2", name:"Silver",    role:"Rival — Mahogany Town",      badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"haunter",level:28},{name:"sneasel",level:28},{name:"golbat",level:28},{name:"quilava",level:30}]},
        {id:"silver-r3", name:"Silver",    role:"Rival — Victory Road",       badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"sneasel",level:36},{name:"golbat",level:38},{name:"haunter",level:36},{name:"magneton",level:36},{name:"typhlosion",level:40}]},
        // Villains
        {id:"archer",    name:"Archer",    role:"Team Rocket Executive — Radio Tower", badge:null, specialType:"dark", category:"villain",
          team:[{name:"houndour",level:20},{name:"weezing",level:24},{name:"houndoom",level:30}]},
        {id:"ariana",    name:"Ariana",    role:"Team Rocket Executive — Mahogany",   badge:null, specialType:"poison", category:"villain",
          team:[{name:"arbok",level:20},{name:"vileplume",level:23},{name:"murkrow",level:23}]},
        {id:"proton",    name:"Proton",    role:"Team Rocket Executive — Slowpoke Well", badge:null, specialType:"poison", category:"villain",
          team:[{name:"golbat",level:19},{name:"weezing",level:23}]},
        {id:"petrel",    name:"Petrel",    role:"Team Rocket Executive — Radio Tower",  badge:null, specialType:"poison", category:"villain",
          team:[{name:"koffing",level:22},{name:"koffing",level:22},{name:"weezing",level:26},{name:"koffing",level:22},{name:"koffing",level:22}]},
      ],
      gsc:[
        {id:"falkner-gsc",  name:"Falkner",  role:"Gym Leader #1",  badge:"Zephyr Badge",  specialType:"flying",   category:"gym",
          team:[{name:"pidgey",level:7},{name:"pidgeotto",level:9}]},
        {id:"bugsy-gsc",    name:"Bugsy",    role:"Gym Leader #2",  badge:"Hive Badge",    specialType:"bug",      category:"gym",
          team:[{name:"metapod",level:14},{name:"kakuna",level:14},{name:"scyther",level:16}]},
        {id:"whitney-gsc",  name:"Whitney",  role:"Gym Leader #3",  badge:"Plain Badge",   specialType:"normal",   category:"gym",
          team:[{name:"clefairy",level:17},{name:"miltank",level:19}]},
        {id:"morty-gsc",    name:"Morty",    role:"Gym Leader #4",  badge:"Fog Badge",     specialType:"ghost",    category:"gym",
          team:[{name:"gastly",level:21},{name:"haunter",level:21},{name:"haunter",level:23},{name:"gengar",level:25}]},
        {id:"chuck-gsc",    name:"Chuck",    role:"Gym Leader #5",  badge:"Storm Badge",   specialType:"fighting", category:"gym",
          team:[{name:"primeape",level:27},{name:"poliwrath",level:30}]},
        {id:"jasmine-gsc",  name:"Jasmine",  role:"Gym Leader #6",  badge:"Mineral Badge", specialType:"steel",    category:"gym",
          team:[{name:"magnemite",level:30},{name:"magnemite",level:30},{name:"steelix",level:35}]},
        {id:"pryce-gsc",    name:"Pryce",    role:"Gym Leader #7",  badge:"Glacier Badge", specialType:"ice",      category:"gym",
          team:[{name:"seel",level:27},{name:"dewgong",level:29},{name:"piloswine",level:31}]},
        {id:"clair-gsc",    name:"Clair",    role:"Gym Leader #8",  badge:"Rising Badge",  specialType:"dragon",   category:"gym",
          team:[{name:"dragonair",level:37},{name:"dragonair",level:37},{name:"kingdra",level:40}]},
        {id:"will-gsc",     name:"Will",     role:"Elite Four #1",  badge:null,            specialType:"psychic",  category:"elite4",
          team:[{name:"xatu",level:40},{name:"jynx",level:41},{name:"slowbro",level:41},{name:"exeggutor",level:41},{name:"xatu",level:42}]},
        {id:"koga-gsc",     name:"Koga",     role:"Elite Four #2",  badge:null,            specialType:"poison",   category:"elite4",
          team:[{name:"ariados",level:40},{name:"venomoth",level:41},{name:"forretress",level:43},{name:"muk",level:42},{name:"crobat",level:44}]},
        {id:"bruno-gsc",    name:"Bruno",    role:"Elite Four #3",  badge:null,            specialType:"fighting", category:"elite4",
          team:[{name:"hitmontop",level:42},{name:"hitmonlee",level:42},{name:"hitmonchan",level:42},{name:"onix",level:43},{name:"machamp",level:46}]},
        {id:"karen-gsc",    name:"Karen",    role:"Elite Four #4",  badge:null,            specialType:"dark",     category:"elite4",
          team:[{name:"umbreon",level:42},{name:"vileplume",level:42},{name:"gengar",level:45},{name:"murkrow",level:44},{name:"houndoom",level:47}]},
        {id:"lance-gsc",    name:"Lance",    role:"Champion",       badge:null,            specialType:"dragon",   category:"champion",
          team:[{name:"gyarados",level:44},{name:"dragonite",level:47},{name:"dragonite",level:47},{name:"aerodactyl",level:46},{name:"charizard",level:46},{name:"dragonite",level:50}]},
        {id:"silver-r1-gsc",name:"Silver",   role:"Rival — Violet City",       badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"gastly",level:12},{name:"cyndaquil",level:14}]},
        {id:"silver-r2-gsc",name:"Silver",   role:"Rival — Ecruteak City",     badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"haunter",level:22},{name:"sneasel",level:20},{name:"magnemite",level:20},{name:"quilava",level:24}]},
        {id:"silver-r3-gsc",name:"Silver",   role:"Rival — Victory Road",      badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"sneasel",level:36},{name:"golbat",level:36},{name:"haunter",level:34},{name:"magneton",level:34},{name:"typhlosion",level:38}]},
        {id:"rocket-exec",  name:"Rocket Executive",role:"Team Rocket — Radio Tower",badge:null,specialType:"poison",category:"villain",
          team:[{name:"arbok",level:26},{name:"vileplume",level:27},{name:"murkrow",level:28},{name:"houndoom",level:30}]},
      ]
    }
  },

  3: {
    name:"Generation III", region:"Hoenn",
    games:[{id:"oras",name:"Omega Ruby / Alpha Sapphire"},{id:"rs",name:"Ruby / Sapphire"},{id:"emerald",name:"Emerald"}],
    opponents:{
      oras:[
        {id:"roxanne",  name:"Roxanne",   role:"Gym Leader #1",  badge:"Stone Badge",   specialType:"rock",     category:"gym",
          team:[{name:"geodude",level:14},{name:"geodude",level:14},{name:"nosepass",level:15}]},
        {id:"brawly",   name:"Brawly",    role:"Gym Leader #2",  badge:"Knuckle Badge", specialType:"fighting", category:"gym",
          team:[{name:"machop",level:16},{name:"meditite",level:16},{name:"makuhita",level:18}]},
        {id:"wattson",  name:"Wattson",   role:"Gym Leader #3",  badge:"Dynamo Badge",  specialType:"electric", category:"gym",
          team:[{name:"voltorb",level:20},{name:"electrike",level:20},{name:"manectric",level:22},{name:"magneton",level:22}]},
        {id:"flannery", name:"Flannery",  role:"Gym Leader #4",  badge:"Heat Badge",    specialType:"fire",     category:"gym",
          team:[{name:"slugma",level:26},{name:"slugma",level:26},{name:"torkoal",level:28},{name:"camerupt",level:29}]},
        {id:"norman",   name:"Norman",    role:"Gym Leader #5",  badge:"Balance Badge", specialType:"normal",   category:"gym",
          team:[{name:"spinda",level:27},{name:"vigoroth",level:27},{name:"linoone",level:29},{name:"slaking",level:31}]},
        {id:"winona",   name:"Winona",    role:"Gym Leader #6",  badge:"Feather Badge", specialType:"flying",   category:"gym",
          team:[{name:"swablu",level:31},{name:"tropius",level:29},{name:"pelipper",level:30},{name:"skarmory",level:32},{name:"altaria",level:33}]},
        {id:"tateliza", name:"Tate & Liza",role:"Gym Leader #7", badge:"Mind Badge",   specialType:"psychic",  category:"gym",
          team:[{name:"solrock",level:45},{name:"lunatone",level:45},{name:"claydol",level:45},{name:"xatu",level:45}]},
        {id:"juan",     name:"Juan",      role:"Gym Leader #8",  badge:"Rain Badge",    specialType:"water",    category:"gym",
          team:[{name:"luvdisc",level:39},{name:"whiscash",level:39},{name:"sealeo",level:40},{name:"crawdaunt",level:41},{name:"kingdra",level:46}]},
        {id:"sidney",   name:"Sidney",    role:"Elite Four #1",  badge:null,            specialType:"dark",     category:"elite4",
          team:[{name:"mightyena",level:46},{name:"shiftry",level:48},{name:"cacturne",level:46},{name:"crawdaunt",level:48},{name:"absol",level:49}]},
        {id:"phoebe",   name:"Phoebe",    role:"Elite Four #2",  badge:null,            specialType:"ghost",    category:"elite4",
          team:[{name:"dusclops",level:48},{name:"banette",level:49},{name:"sableye",level:50},{name:"banette",level:49},{name:"dusknoir",level:51}]},
        {id:"glacia",   name:"Glacia",    role:"Elite Four #3",  badge:null,            specialType:"ice",      category:"elite4",
          team:[{name:"glalie",level:50},{name:"sealeo",level:50},{name:"sealeo",level:52},{name:"glalie",level:52},{name:"walrein",level:53}]},
        {id:"drake3",   name:"Drake",     role:"Elite Four #4",  badge:null,            specialType:"dragon",   category:"elite4",
          team:[{name:"shelgon",level:52},{name:"altaria",level:54},{name:"flygon",level:53},{name:"flygon",level:53},{name:"salamence",level:55}]},
        {id:"steven",   name:"Steven",    role:"Champion",       badge:null,            specialType:"steel",    category:"champion",
          team:[{name:"skarmory",level:57},{name:"aggron",level:57},{name:"claydol",level:57},{name:"cradily",level:57},{name:"armaldo",level:57},{name:"metagross",level:59}]},
        // Rivals
        {id:"may-r1",   name:"May",       role:"Rival — Route 110",         badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"grovyle",level:18},{name:"wingull",level:16}]},
        {id:"may-r2",   name:"May",       role:"Rival — Route 119",         badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"grovyle",level:29},{name:"wailmer",level:26},{name:"slugma",level:25}]},
        {id:"may-r3",   name:"May",       role:"Rival — Lilycove City",     badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"sceptile",level:35},{name:"wailmer",level:33},{name:"slugma",level:32},{name:"numel",level:30}]},
        // Villains
        {id:"tabitha",  name:"Tabitha",   role:"Team Magma Admin — Mt. Chimney", badge:null,specialType:"fire", category:"villain",
          team:[{name:"mightyena",level:26},{name:"numel",level:28},{name:"torkoal",level:29}]},
        {id:"maxie",    name:"Maxie",     role:"Team Magma Leader — Seafloor Cavern", badge:null, specialType:"fire", category:"villain",
          team:[{name:"mightyena",level:40},{name:"crobat",level:43},{name:"camerupt",level:46}]},
        {id:"shelly",   name:"Shelly",    role:"Team Aqua Admin",           badge:null, specialType:"water",   category:"villain",
          team:[{name:"mightyena",level:28},{name:"sharpedo",level:30}]},
        {id:"archie",   name:"Archie",    role:"Team Aqua Leader — Seafloor Cavern", badge:null, specialType:"water", category:"villain",
          team:[{name:"mightyena",level:41},{name:"crobat",level:43},{name:"sharpedo",level:46}]},
      ],
      rs:[
        {id:"roxanne-rs", name:"Roxanne", role:"Gym Leader #1",  badge:"Stone Badge",   specialType:"rock",     category:"gym",
          team:[{name:"geodude",level:14},{name:"geodude",level:14},{name:"nosepass",level:15}]},
        {id:"brawly-rs",  name:"Brawly",  role:"Gym Leader #2",  badge:"Knuckle Badge", specialType:"fighting", category:"gym",
          team:[{name:"machop",level:17},{name:"makuhita",level:17},{name:"hariyama",level:19}]},
        {id:"wattson-rs", name:"Wattson", role:"Gym Leader #3",  badge:"Dynamo Badge",  specialType:"electric", category:"gym",
          team:[{name:"magnemite",level:20},{name:"voltorb",level:20},{name:"magneton",level:22}]},
        {id:"flannery-rs",name:"Flannery",role:"Gym Leader #4",  badge:"Heat Badge",    specialType:"fire",     category:"gym",
          team:[{name:"slugma",level:24},{name:"slugma",level:24},{name:"camerupt",level:28}]},
        {id:"norman-rs",  name:"Norman",  role:"Gym Leader #5",  badge:"Balance Badge", specialType:"normal",   category:"gym",
          team:[{name:"spinda",level:27},{name:"vigoroth",level:27},{name:"vigoroth",level:27},{name:"slaking",level:31}]},
        {id:"winona-rs",  name:"Winona",  role:"Gym Leader #6",  badge:"Feather Badge", specialType:"flying",   category:"gym",
          team:[{name:"swablu",level:29},{name:"tropius",level:28},{name:"pelipper",level:30},{name:"skarmory",level:31},{name:"altaria",level:33}]},
        {id:"tateliza-rs",name:"Tate & Liza",role:"Gym Leader #7",badge:"Mind Badge",  specialType:"psychic",  category:"gym",
          team:[{name:"solrock",level:41},{name:"lunatone",level:41}]},
        {id:"wallace-rs", name:"Wallace", role:"Gym Leader #8",  badge:"Rain Badge",    specialType:"water",    category:"gym",
          team:[{name:"luvdisc",level:40},{name:"whiscash",level:42},{name:"sealeo",level:40},{name:"seaking",level:40},{name:"milotic",level:42}]},
        {id:"sidney-rs",  name:"Sidney",  role:"Elite Four #1",  badge:null,            specialType:"dark",     category:"elite4",
          team:[{name:"mightyena",level:46},{name:"shiftry",level:48},{name:"cacturne",level:46},{name:"crawdaunt",level:48},{name:"absol",level:49}]},
        {id:"phoebe-rs",  name:"Phoebe",  role:"Elite Four #2",  badge:null,            specialType:"ghost",    category:"elite4",
          team:[{name:"dusclops",level:48},{name:"banette",level:49},{name:"sableye",level:50},{name:"banette",level:49},{name:"dusclops",level:51}]},
        {id:"glacia-rs",  name:"Glacia",  role:"Elite Four #3",  badge:null,            specialType:"ice",      category:"elite4",
          team:[{name:"glalie",level:50},{name:"sealeo",level:50},{name:"sealeo",level:52},{name:"glalie",level:52},{name:"walrein",level:53}]},
        {id:"drake-rs",   name:"Drake",   role:"Elite Four #4",  badge:null,            specialType:"dragon",   category:"elite4",
          team:[{name:"shelgon",level:52},{name:"altaria",level:54},{name:"flygon",level:53},{name:"flygon",level:53},{name:"salamence",level:55}]},
        {id:"steven-rs",  name:"Steven",  role:"Champion",       badge:null,            specialType:"steel",    category:"champion",
          team:[{name:"skarmory",level:57},{name:"claydol",level:57},{name:"aggron",level:57},{name:"cradily",level:57},{name:"armaldo",level:57},{name:"metagross",level:59}]},
        {id:"may-r1-rs",  name:"May",     role:"Rival — Route 110",        badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"grovyle",level:18},{name:"wingull",level:16}]},
        {id:"may-r2-rs",  name:"May",     role:"Rival — Route 119",        badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"grovyle",level:29},{name:"wailmer",level:26},{name:"slugma",level:25}]},
        {id:"maxie-rs",   name:"Maxie",   role:"Team Magma Leader — Mt. Chimney", badge:null, specialType:"fire", category:"villain",
          team:[{name:"mightyena",level:30},{name:"zubat",level:31},{name:"camerupt",level:33}]},
        {id:"archie-rs",  name:"Archie",  role:"Team Aqua Leader — Seafloor Cavern", badge:null, specialType:"water", category:"villain",
          team:[{name:"mightyena",level:39},{name:"crobat",level:41},{name:"sharpedo",level:43}]},
      ],
      emerald:[
        {id:"roxanne-e", name:"Roxanne",  role:"Gym Leader #1",  badge:"Stone Badge",   specialType:"rock",     category:"gym",
          team:[{name:"geodude",level:14},{name:"geodude",level:14},{name:"nosepass",level:15}]},
        {id:"brawly-e",  name:"Brawly",   role:"Gym Leader #2",  badge:"Knuckle Badge", specialType:"fighting", category:"gym",
          team:[{name:"machop",level:17},{name:"meditite",level:17},{name:"makuhita",level:19}]},
        {id:"wattson-e", name:"Wattson",  role:"Gym Leader #3",  badge:"Dynamo Badge",  specialType:"electric", category:"gym",
          team:[{name:"voltorb",level:20},{name:"electrike",level:20},{name:"magneton",level:22},{name:"manectric",level:24}]},
        {id:"flannery-e",name:"Flannery", role:"Gym Leader #4",  badge:"Heat Badge",    specialType:"fire",     category:"gym",
          team:[{name:"numel",level:26},{name:"slugma",level:26},{name:"camerupt",level:28},{name:"torkoal",level:29}]},
        {id:"norman-e",  name:"Norman",   role:"Gym Leader #5",  badge:"Balance Badge", specialType:"normal",   category:"gym",
          team:[{name:"spinda",level:27},{name:"vigoroth",level:27},{name:"linoone",level:29},{name:"slaking",level:31}]},
        {id:"winona-e",  name:"Winona",   role:"Gym Leader #6",  badge:"Feather Badge", specialType:"flying",   category:"gym",
          team:[{name:"swablu",level:31},{name:"tropius",level:29},{name:"pelipper",level:30},{name:"skarmory",level:32},{name:"altaria",level:33}]},
        {id:"tateliza-e",name:"Tate & Liza",role:"Gym Leader #7",badge:"Mind Badge",   specialType:"psychic",  category:"gym",
          team:[{name:"claydol",level:41},{name:"solrock",level:42},{name:"lunatone",level:42},{name:"xatu",level:41}]},
        {id:"juan-e",    name:"Juan",     role:"Gym Leader #8",  badge:"Rain Badge",    specialType:"water",    category:"gym",
          team:[{name:"luvdisc",level:41},{name:"whiscash",level:41},{name:"sealeo",level:43},{name:"crawdaunt",level:43},{name:"kingdra",level:46}]},
        {id:"sidney-e",  name:"Sidney",   role:"Elite Four #1",  badge:null,            specialType:"dark",     category:"elite4",
          team:[{name:"mightyena",level:46},{name:"shiftry",level:48},{name:"cacturne",level:46},{name:"crawdaunt",level:48},{name:"absol",level:50}]},
        {id:"phoebe-e",  name:"Phoebe",   role:"Elite Four #2",  badge:null,            specialType:"ghost",    category:"elite4",
          team:[{name:"dusclops",level:48},{name:"banette",level:49},{name:"sableye",level:50},{name:"banette",level:49},{name:"dusknoir",level:51}]},
        {id:"glacia-e",  name:"Glacia",   role:"Elite Four #3",  badge:null,            specialType:"ice",      category:"elite4",
          team:[{name:"glalie",level:50},{name:"sealeo",level:50},{name:"sealeo",level:52},{name:"glalie",level:52},{name:"walrein",level:53}]},
        {id:"drake-e",   name:"Drake",    role:"Elite Four #4",  badge:null,            specialType:"dragon",   category:"elite4",
          team:[{name:"shelgon",level:52},{name:"altaria",level:54},{name:"flygon",level:53},{name:"flygon",level:53},{name:"salamence",level:55}]},
        {id:"wallace-e", name:"Wallace",  role:"Champion",       badge:null,            specialType:"water",    category:"champion",
          team:[{name:"milotic",level:57},{name:"tentacruel",level:55},{name:"ludicolo",level:56},{name:"whiscash",level:56},{name:"gyarados",level:56},{name:"starmie",level:57}]},
        {id:"may-r1-e",  name:"May",      role:"Rival — Route 110",        badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"grovyle",level:18},{name:"wingull",level:16}]},
        {id:"may-r2-e",  name:"May",      role:"Rival — Route 119",        badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"grovyle",level:28},{name:"wailmer",level:26},{name:"slugma",level:25}]},
        {id:"may-r3-e",  name:"May",      role:"Rival — Mossdeep City",    badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"sceptile",level:36},{name:"wailord",level:34},{name:"camerupt",level:33},{name:"magneton",level:31}]},
        {id:"maxie-e",   name:"Maxie",    role:"Team Magma Leader — Magma Hideout", badge:null, specialType:"fire", category:"villain",
          team:[{name:"mightyena",level:42},{name:"crobat",level:43},{name:"camerupt",level:46}]},
        {id:"tabitha-e", name:"Tabitha",  role:"Team Magma Admin — Weather Institute", badge:null, specialType:"fire", category:"villain",
          team:[{name:"mightyena",level:31},{name:"mightyena",level:33},{name:"camerupt",level:35}]},
        {id:"archie-e",  name:"Archie",   role:"Team Aqua Leader — Aqua Hideout",  badge:null, specialType:"water", category:"villain",
          team:[{name:"mightyena",level:42},{name:"crobat",level:44},{name:"sharpedo",level:46}]},
        {id:"shelly-e",  name:"Shelly",   role:"Team Aqua Admin — Weather Institute", badge:null, specialType:"water", category:"villain",
          team:[{name:"mightyena",level:35},{name:"sharpedo",level:38}]},
      ]
    }
  },

  4: {
    name:"Generation IV", region:"Sinnoh",
    games:[{id:"platinum",name:"Platinum"},{id:"dp",name:"Diamond / Pearl"},{id:"bdsp",name:"Brilliant Diamond / Shining Pearl"}],
    opponents:{
      platinum:[
        {id:"roark-pt",  name:"Roark",    role:"Gym Leader #1",  badge:"Coal Badge",    specialType:"rock",     category:"gym",
          team:[{name:"geodude",level:12},{name:"onix",level:12},{name:"cranidos",level:14}]},
        {id:"gardenia-pt",name:"Gardenia",role:"Gym Leader #2",  badge:"Forest Badge",  specialType:"grass",    category:"gym",
          team:[{name:"turtwig",level:20},{name:"cherubi",level:20},{name:"roserade",level:22}]},
        {id:"maylene-pt",name:"Maylene",  role:"Gym Leader #3",  badge:"Cobble Badge",  specialType:"fighting", category:"gym",
          team:[{name:"meditite",level:28},{name:"machoke",level:29},{name:"lucario",level:32}]},
        {id:"wake-pt",   name:"Crasher Wake",role:"Gym Leader #4",badge:"Fen Badge",    specialType:"water",    category:"gym",
          team:[{name:"gyarados",level:33},{name:"quagsire",level:34},{name:"floatzel",level:37}]},
        {id:"fantina-pt",name:"Fantina",  role:"Gym Leader #5",  badge:"Relic Badge",   specialType:"ghost",    category:"gym",
          team:[{name:"haunter",level:32},{name:"gengar",level:34},{name:"mismagius",level:36}]},
        {id:"byron-pt",  name:"Byron",    role:"Gym Leader #6",  badge:"Mine Badge",    specialType:"steel",    category:"gym",
          team:[{name:"magneton",level:37},{name:"steelix",level:38},{name:"bastiodon",level:41}]},
        {id:"candice-pt",name:"Candice",  role:"Gym Leader #7",  badge:"Icicle Badge",  specialType:"ice",      category:"gym",
          team:[{name:"snover",level:38},{name:"sneasel",level:38},{name:"medicham",level:40},{name:"abomasnow",level:42}]},
        {id:"volkner-pt",name:"Volkner",  role:"Gym Leader #8",  badge:"Beacon Badge",  specialType:"electric", category:"gym",
          team:[{name:"jolteon",level:46},{name:"raichu",level:46},{name:"ambipom",level:46},{name:"luxray",level:48},{name:"electivire",level:50}]},
        {id:"aaron-pt",  name:"Aaron",    role:"Elite Four #1",  badge:null,            specialType:"bug",      category:"elite4",
          team:[{name:"dustox",level:53},{name:"beautifly",level:53},{name:"vespiquen",level:54},{name:"heracross",level:54},{name:"drapion",level:57}]},
        {id:"bertha-pt", name:"Bertha",   role:"Elite Four #2",  badge:null,            specialType:"ground",   category:"elite4",
          team:[{name:"whiscash",level:55},{name:"gliscor",level:55},{name:"golem",level:56},{name:"rhyperior",level:58},{name:"hippowdon",level:59}]},
        {id:"flint-pt",  name:"Flint",    role:"Elite Four #3",  badge:null,            specialType:"fire",     category:"elite4",
          team:[{name:"houndoom",level:54},{name:"rapidash",level:55},{name:"flareon",level:55},{name:"infernape",level:58},{name:"magmortar",level:57}]},
        {id:"lucian-pt", name:"Lucian",   role:"Elite Four #4",  badge:null,            specialType:"psychic",  category:"elite4",
          team:[{name:"mr-mime",level:53},{name:"espeon",level:55},{name:"bronzong",level:54},{name:"alakazam",level:56},{name:"gallade",level:59}]},
        {id:"cynthia-pt",name:"Cynthia",  role:"Champion",       badge:null,            specialType:"mixed",    category:"champion",
          team:[{name:"spiritomb",level:58},{name:"roserade",level:58},{name:"togekiss",level:60},{name:"lucario",level:60},{name:"milotic",level:58},{name:"garchomp",level:62}]},
        // Rivals
        {id:"barry-r1",  name:"Barry",    role:"Rival — Jubilife City",     badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"starly",level:9},{name:"piplup",level:9}]},
        {id:"barry-r2",  name:"Barry",    role:"Rival — Hearthome City",    badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"staravia",level:26},{name:"prinplup",level:27},{name:"buizel",level:25},{name:"ponyta",level:25}]},
        {id:"barry-r3",  name:"Barry",    role:"Rival — Victory Road",      badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"heracross",level:47},{name:"rapidash",level:47},{name:"staraptor",level:49},{name:"roserade",level:49},{name:"snorlax",level:51},{name:"empoleon",level:51}]},
        // Villains
        {id:"mars-pt",   name:"Mars",     role:"Team Galactic Commander — Lake Verity", badge:null, specialType:"poison", category:"villain",
          team:[{name:"zubat",level:19},{name:"purugly",level:21}]},
        {id:"jupiter-pt",name:"Jupiter",  role:"Team Galactic Commander — Lake Acuity", badge:null, specialType:"poison", category:"villain",
          team:[{name:"sneasel",level:35},{name:"golbat",level:37},{name:"skuntank",level:38}]},
        {id:"saturn-pt", name:"Saturn",   role:"Team Galactic Commander — Iron Island", badge:null, specialType:"poison", category:"villain",
          team:[{name:"bronzor",level:28},{name:"toxicroak",level:28}]},
        {id:"cyrus-pt1", name:"Cyrus",    role:"Team Galactic Leader — Mt. Coronet",    badge:null, specialType:"dark",   category:"villain",
          team:[{name:"sneasel",level:44},{name:"golbat",level:46},{name:"murkrow",level:44},{name:"honchkrow",level:48}]},
        {id:"cyrus-pt2", name:"Cyrus",    role:"Team Galactic Leader — Distortion World",badge:null,specialType:"dark",  category:"villain",
          team:[{name:"houndoom",level:52},{name:"honchkrow",level:54},{name:"crobat",level:54},{name:"gyarados",level:56},{name:"weavile",level:58}]},
      ],
      dp:[
        {id:"roark-dp",  name:"Roark",    role:"Gym Leader #1",  badge:"Coal Badge",    specialType:"rock",     category:"gym",
          team:[{name:"geodude",level:12},{name:"onix",level:12},{name:"cranidos",level:14}]},
        {id:"gardenia-dp",name:"Gardenia",role:"Gym Leader #2",  badge:"Forest Badge",  specialType:"grass",    category:"gym",
          team:[{name:"cherubi",level:19},{name:"roserade",level:22}]},
        {id:"maylene-dp",name:"Maylene",  role:"Gym Leader #3",  badge:"Cobble Badge",  specialType:"fighting", category:"gym",
          team:[{name:"meditite",level:27},{name:"machoke",level:27},{name:"lucario",level:30}]},
        {id:"wake-dp",   name:"Crasher Wake",role:"Gym Leader #4",badge:"Fen Badge",    specialType:"water",    category:"gym",
          team:[{name:"gyarados",level:27},{name:"quagsire",level:27},{name:"floatzel",level:30}]},
        {id:"fantina-dp",name:"Fantina",  role:"Gym Leader #5",  badge:"Relic Badge",   specialType:"ghost",    category:"gym",
          team:[{name:"misdreavus",level:24},{name:"haunter",level:24},{name:"mismagius",level:26}]},
        {id:"byron-dp",  name:"Byron",    role:"Gym Leader #6",  badge:"Mine Badge",    specialType:"steel",    category:"gym",
          team:[{name:"bronzor",level:36},{name:"steelix",level:36},{name:"bastiodon",level:39}]},
        {id:"candice-dp",name:"Candice",  role:"Gym Leader #7",  badge:"Icicle Badge",  specialType:"ice",      category:"gym",
          team:[{name:"snover",level:38},{name:"sneasel",level:38},{name:"medicham",level:40},{name:"abomasnow",level:42}]},
        {id:"volkner-dp",name:"Volkner",  role:"Gym Leader #8",  badge:"Beacon Badge",  specialType:"electric", category:"gym",
          team:[{name:"jolteon",level:46},{name:"raichu",level:46},{name:"luxray",level:48},{name:"electivire",level:50}]},
        {id:"aaron-dp",  name:"Aaron",    role:"Elite Four #1",  badge:null,            specialType:"bug",      category:"elite4",
          team:[{name:"dustox",level:53},{name:"beautifly",level:53},{name:"vespiquen",level:54},{name:"heracross",level:54},{name:"drapion",level:57}]},
        {id:"bertha-dp", name:"Bertha",   role:"Elite Four #2",  badge:null,            specialType:"ground",   category:"elite4",
          team:[{name:"whiscash",level:55},{name:"gliscor",level:55},{name:"golem",level:56},{name:"rhyperior",level:58},{name:"hippowdon",level:59}]},
        {id:"flint-dp",  name:"Flint",    role:"Elite Four #3 (mixed team in DP)", badge:null, specialType:"fire", category:"elite4",
          team:[{name:"drifblim",level:53},{name:"lopunny",level:54},{name:"steelix",level:57},{name:"roserade",level:54},{name:"infernape",level:58}]},
        {id:"lucian-dp", name:"Lucian",   role:"Elite Four #4",  badge:null,            specialType:"psychic",  category:"elite4",
          team:[{name:"mr-mime",level:53},{name:"espeon",level:55},{name:"bronzong",level:54},{name:"alakazam",level:56},{name:"gallade",level:59}]},
        {id:"cynthia-dp",name:"Cynthia",  role:"Champion",       badge:null,            specialType:"mixed",    category:"champion",
          team:[{name:"spiritomb",level:58},{name:"roserade",level:58},{name:"togekiss",level:60},{name:"lucario",level:60},{name:"milotic",level:58},{name:"garchomp",level:62}]},
        {id:"barry-r1-dp",name:"Barry",   role:"Rival — Jubilife City",    badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"starly",level:9},{name:"piplup",level:9}]},
        {id:"barry-r2-dp",name:"Barry",   role:"Rival — Hearthome City",   badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"staravia",level:24},{name:"prinplup",level:25},{name:"buizel",level:23}]},
        {id:"barry-r3-dp",name:"Barry",   role:"Rival — Victory Road",     badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"heracross",level:47},{name:"rapidash",level:47},{name:"staraptor",level:49},{name:"roserade",level:49},{name:"snorlax",level:51},{name:"empoleon",level:51}]},
        {id:"cyrus-dp1", name:"Cyrus",    role:"Team Galactic Leader — Celestic Town", badge:null, specialType:"dark", category:"villain",
          team:[{name:"golbat",level:40},{name:"murkrow",level:41},{name:"sneasel",level:40},{name:"honchkrow",level:45}]},
        {id:"cyrus-dp2", name:"Cyrus",    role:"Team Galactic Leader — Spear Pillar",  badge:null, specialType:"dark", category:"villain",
          team:[{name:"sneasel",level:44},{name:"golbat",level:46},{name:"murkrow",level:46},{name:"honchkrow",level:48}]},
        {id:"mars-dp",   name:"Mars",     role:"Team Galactic Commander",   badge:null, specialType:"poison",  category:"villain",
          team:[{name:"zubat",level:19},{name:"purugly",level:21}]},
      ],
      bdsp:[
        {id:"roark-bdsp",  name:"Roark",    role:"Gym Leader #1",  badge:"Coal Badge",    specialType:"rock",     category:"gym",
          team:[{name:"geodude",level:12},{name:"onix",level:12},{name:"cranidos",level:14}]},
        {id:"gardenia-bdsp",name:"Gardenia",role:"Gym Leader #2",  badge:"Forest Badge",  specialType:"grass",    category:"gym",
          team:[{name:"cherubi",level:19},{name:"roserade",level:22}]},
        {id:"maylene-bdsp",name:"Maylene",  role:"Gym Leader #3",  badge:"Cobble Badge",  specialType:"fighting", category:"gym",
          team:[{name:"meditite",level:27},{name:"machoke",level:27},{name:"lucario",level:30}]},
        {id:"wake-bdsp",   name:"Crasher Wake",role:"Gym Leader #4",badge:"Fen Badge",    specialType:"water",    category:"gym",
          team:[{name:"gyarados",level:27},{name:"quagsire",level:27},{name:"floatzel",level:30}]},
        {id:"fantina-bdsp",name:"Fantina",  role:"Gym Leader #5",  badge:"Relic Badge",   specialType:"ghost",    category:"gym",
          team:[{name:"misdreavus",level:24},{name:"haunter",level:24},{name:"mismagius",level:26}]},
        {id:"byron-bdsp",  name:"Byron",    role:"Gym Leader #6",  badge:"Mine Badge",    specialType:"steel",    category:"gym",
          team:[{name:"bronzor",level:36},{name:"steelix",level:36},{name:"bastiodon",level:39}]},
        {id:"candice-bdsp",name:"Candice",  role:"Gym Leader #7",  badge:"Icicle Badge",  specialType:"ice",      category:"gym",
          team:[{name:"snover",level:38},{name:"sneasel",level:38},{name:"medicham",level:40},{name:"abomasnow",level:42}]},
        {id:"volkner-bdsp",name:"Volkner",  role:"Gym Leader #8",  badge:"Beacon Badge",  specialType:"electric", category:"gym",
          team:[{name:"jolteon",level:46},{name:"raichu",level:46},{name:"luxray",level:48},{name:"electivire",level:50}]},
        {id:"aaron-bdsp",  name:"Aaron",    role:"Elite Four #1",  badge:null,            specialType:"bug",      category:"elite4",
          team:[{name:"dustox",level:53},{name:"beautifly",level:53},{name:"vespiquen",level:54},{name:"heracross",level:54},{name:"drapion",level:57}]},
        {id:"bertha-bdsp", name:"Bertha",   role:"Elite Four #2",  badge:null,            specialType:"ground",   category:"elite4",
          team:[{name:"whiscash",level:55},{name:"gliscor",level:55},{name:"golem",level:56},{name:"rhyperior",level:58},{name:"hippowdon",level:59}]},
        {id:"flint-bdsp",  name:"Flint",    role:"Elite Four #3 (mixed team)",badge:null, specialType:"fire",     category:"elite4",
          team:[{name:"drifblim",level:53},{name:"lopunny",level:54},{name:"steelix",level:57},{name:"roserade",level:54},{name:"infernape",level:58}]},
        {id:"lucian-bdsp", name:"Lucian",   role:"Elite Four #4",  badge:null,            specialType:"psychic",  category:"elite4",
          team:[{name:"mr-mime",level:53},{name:"espeon",level:55},{name:"bronzong",level:54},{name:"alakazam",level:56},{name:"gallade",level:59}]},
        {id:"cynthia-bdsp",name:"Cynthia",  role:"Champion",       badge:null,            specialType:"mixed",    category:"champion",
          team:[{name:"spiritomb",level:58},{name:"roserade",level:58},{name:"togekiss",level:60},{name:"lucario",level:60},{name:"milotic",level:58},{name:"garchomp",level:62}]},
        {id:"barry-r1-bdsp",name:"Barry",   role:"Rival — Jubilife City",   badge:null, specialType:"mixed",     category:"rival",
          team:[{name:"starly",level:9},{name:"piplup",level:9}]},
        {id:"barry-r3-bdsp",name:"Barry",   role:"Rival — Victory Road",    badge:null, specialType:"mixed",     category:"rival",
          team:[{name:"heracross",level:47},{name:"rapidash",level:47},{name:"staraptor",level:49},{name:"roserade",level:49},{name:"snorlax",level:51},{name:"empoleon",level:51}]},
        {id:"cyrus-bdsp",  name:"Cyrus",    role:"Team Galactic Leader — Spear Pillar", badge:null, specialType:"dark", category:"villain",
          team:[{name:"sneasel",level:44},{name:"golbat",level:46},{name:"murkrow",level:46},{name:"honchkrow",level:48}]},
      ]
    }
  },

  5: {
    name:"Generation V", region:"Unova",
    games:[{id:"bw2",name:"Black 2 / White 2"},{id:"bw",name:"Black / White"}],
    opponents:{
      bw2:[
        {id:"roxie",    name:"Roxie",     role:"Gym Leader #1",  badge:"Toxic Badge",   specialType:"poison",   category:"gym",
          team:[{name:"koffing",level:16},{name:"whirlipede",level:18}]},
        {id:"burgh",    name:"Burgh",     role:"Gym Leader #2",  badge:"Insect Badge",  specialType:"bug",      category:"gym",
          team:[{name:"swadloon",level:20},{name:"dwebble",level:21},{name:"leavanny",level:23}]},
        {id:"elesa",    name:"Elesa",     role:"Gym Leader #3",  badge:"Bolt Badge",    specialType:"electric", category:"gym",
          team:[{name:"emolga",level:25},{name:"flaaffy",level:25},{name:"emolga",level:27},{name:"zebstrika",level:28}]},
        {id:"clay",     name:"Clay",      role:"Gym Leader #4",  badge:"Quake Badge",   specialType:"ground",   category:"gym",
          team:[{name:"krokorok",level:31},{name:"palpitoad",level:31},{name:"excadrill",level:33}]},
        {id:"skyla",    name:"Skyla",     role:"Gym Leader #5",  badge:"Jet Badge",     specialType:"flying",   category:"gym",
          team:[{name:"swoobat",level:33},{name:"skarmory",level:35},{name:"swanna",level:35},{name:"unfezant",level:37}]},
        {id:"drayden",  name:"Drayden",   role:"Gym Leader #6",  badge:"Legend Badge",  specialType:"dragon",   category:"gym",
          team:[{name:"fraxure",level:46},{name:"flygon",level:46},{name:"haxorus",level:48}]},
        {id:"marlon",   name:"Marlon",    role:"Gym Leader #7",  badge:"Wave Badge",    specialType:"water",    category:"gym",
          team:[{name:"carracosta",level:49},{name:"jellicent",level:49},{name:"wailord",level:51}]},
        {id:"shauntal", name:"Shauntal",  role:"Elite Four #1",  badge:null,            specialType:"ghost",    category:"elite4",
          team:[{name:"cofagrigus",level:56},{name:"drifblim",level:56},{name:"chandelure",level:58},{name:"golurk",level:58}]},
        {id:"grimsley", name:"Grimsley",  role:"Elite Four #2",  badge:null,            specialType:"dark",     category:"elite4",
          team:[{name:"liepard",level:56},{name:"scrafty",level:56},{name:"krookodile",level:58},{name:"bisharp",level:58}]},
        {id:"caitlin",  name:"Caitlin",   role:"Elite Four #3",  badge:null,            specialType:"psychic",  category:"elite4",
          team:[{name:"reuniclus",level:56},{name:"musharna",level:56},{name:"gothitelle",level:58},{name:"sigilyph",level:58}]},
        {id:"marshal",  name:"Marshal",   role:"Elite Four #4",  badge:null,            specialType:"fighting", category:"elite4",
          team:[{name:"throh",level:56},{name:"sawk",level:56},{name:"conkeldurr",level:58},{name:"mienshao",level:58}]},
        {id:"iris",     name:"Iris",      role:"Champion",       badge:null,            specialType:"dragon",   category:"champion",
          team:[{name:"druddigon",level:57},{name:"aggron",level:58},{name:"lapras",level:58},{name:"archeops",level:58},{name:"hydreigon",level:59},{name:"haxorus",level:59}]},
        // Rivals
        {id:"hugh-r1",  name:"Hugh",      role:"Rival — Virbank City",      badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"dewott",level:18},{name:"lillipup",level:16},{name:"pidove",level:16}]},
        {id:"hugh-r2",  name:"Hugh",      role:"Rival — Driftveil City",    badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"samurott",level:35},{name:"swoobat",level:33},{name:"bouffalant",level:32},{name:"simipour",level:33}]},
        {id:"hugh-r3",  name:"Hugh",      role:"Rival — Victory Road",      badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"samurott",level:47},{name:"unfezant",level:45},{name:"bouffalant",level:47},{name:"flygon",level:46},{name:"eelektross",level:46}]},
        {id:"n-bw2",    name:"N",         role:"Rival — Giant Chasm",       badge:null, specialType:"dragon",  category:"rival",
          team:[{name:"zekrom",level:70},{name:"vanilluxe",level:52},{name:"zoroark",level:50},{name:"klinklang",level:50},{name:"carracosta",level:50},{name:"archeops",level:52}]},
        // Villains
        {id:"colress-1",name:"Colress",   role:"Team Plasma Scientist — Route 4",  badge:null, specialType:"steel", category:"villain",
          team:[{name:"magneton",level:36},{name:"klink",level:36},{name:"magneton",level:38},{name:"klingklang",level:40}]},
        {id:"colress-2",name:"Colress",   role:"Team Plasma Scientist — Plasma Frigate", badge:null, specialType:"steel", category:"villain",
          team:[{name:"magnezone",level:52},{name:"magneton",level:54},{name:"beheeyem",level:54},{name:"magnezone",level:56},{name:"klingklang",level:58}]},
        {id:"ghetsis-bw2",name:"Ghetsis", role:"Team Plasma Leader — Giant Chasm", badge:null, specialType:"mixed", category:"villain",
          team:[{name:"cofagrigus",level:50},{name:"seismitoad",level:50},{name:"drapion",level:50},{name:"eelektross",level:50},{name:"toxicroak",level:50},{name:"hydreigon",level:52}]},
      ],
      bw:[
        {id:"cilan-bw",  name:"Cilan",    role:"Gym Leader #1 (Grass)",  badge:"Trio Badge", specialType:"grass",   category:"gym",
          team:[{name:"pansage",level:12},{name:"simisage",level:14}]},
        {id:"lenora-bw", name:"Lenora",   role:"Gym Leader #2",  badge:"Basic Badge",   specialType:"normal",   category:"gym",
          team:[{name:"herdier",level:18},{name:"watchog",level:20}]},
        {id:"burgh-bw",  name:"Burgh",    role:"Gym Leader #3",  badge:"Insect Badge",  specialType:"bug",      category:"gym",
          team:[{name:"whirlipede",level:21},{name:"dwebble",level:21},{name:"leavanny",level:23}]},
        {id:"elesa-bw",  name:"Elesa",    role:"Gym Leader #4",  badge:"Bolt Badge",    specialType:"electric", category:"gym",
          team:[{name:"emolga",level:25},{name:"emolga",level:25},{name:"zebstrika",level:28}]},
        {id:"clay-bw",   name:"Clay",     role:"Gym Leader #5",  badge:"Quake Badge",   specialType:"ground",   category:"gym",
          team:[{name:"krokorok",level:29},{name:"palpitoad",level:29},{name:"excadrill",level:31}]},
        {id:"skyla-bw",  name:"Skyla",    role:"Gym Leader #6",  badge:"Jet Badge",     specialType:"flying",   category:"gym",
          team:[{name:"swoobat",level:33},{name:"unfezant",level:33},{name:"swanna",level:35}]},
        {id:"brycen-bw", name:"Brycen",   role:"Gym Leader #7",  badge:"Freeze Badge",  specialType:"ice",      category:"gym",
          team:[{name:"vanillish",level:37},{name:"cryogonal",level:37},{name:"beartic",level:39}]},
        {id:"drayden-bw",name:"Drayden",  role:"Gym Leader #8",  badge:"Legend Badge",  specialType:"dragon",   category:"gym",
          team:[{name:"fraxure",level:41},{name:"druddigon",level:41},{name:"haxorus",level:43}]},
        {id:"shauntal-bw",name:"Shauntal",role:"Elite Four #1",  badge:null,            specialType:"ghost",    category:"elite4",
          team:[{name:"cofagrigus",level:48},{name:"drifblim",level:48},{name:"chandelure",level:50},{name:"golurk",level:50}]},
        {id:"grimsley-bw",name:"Grimsley",role:"Elite Four #2",  badge:null,            specialType:"dark",     category:"elite4",
          team:[{name:"liepard",level:48},{name:"scrafty",level:48},{name:"krookodile",level:50},{name:"bisharp",level:50}]},
        {id:"caitlin-bw",name:"Caitlin",  role:"Elite Four #3",  badge:null,            specialType:"psychic",  category:"elite4",
          team:[{name:"reuniclus",level:48},{name:"musharna",level:48},{name:"gothitelle",level:50},{name:"sigilyph",level:50}]},
        {id:"marshal-bw",name:"Marshal",  role:"Elite Four #4",  badge:null,            specialType:"fighting", category:"elite4",
          team:[{name:"throh",level:48},{name:"sawk",level:48},{name:"conkeldurr",level:50},{name:"mienshao",level:50}]},
        {id:"alder-bw",  name:"Alder",    role:"Champion",       badge:null,            specialType:"mixed",    category:"champion",
          team:[{name:"accelgor",level:54},{name:"bouffalant",level:54},{name:"druddigon",level:54},{name:"vanilluxe",level:54},{name:"escavalier",level:54},{name:"volcarona",level:56}]},
        // Rivals
        {id:"cheren-r1-bw",name:"Cheren", role:"Rival — Route 5",          badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"servine",level:25},{name:"pansage",level:22},{name:"pidove",level:22}]},
        {id:"cheren-r2-bw",name:"Cheren", role:"Rival — Victory Road",     badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"serperior",level:45},{name:"simisage",level:44},{name:"liepard",level:44},{name:"unfezant",level:44}]},
        {id:"bianca-r1-bw",name:"Bianca", role:"Rival — Nimbasa City",     badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"dewott",level:25},{name:"musharna",level:23},{name:"herdier",level:22}]},
        {id:"bianca-r2-bw",name:"Bianca", role:"Rival — Undella Town",     badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"samurott",level:47},{name:"swoobat",level:46},{name:"musharna",level:45},{name:"stoutland",level:46},{name:"mienshao",level:47}]},
        // Villains
        {id:"n-bw1",    name:"N",         role:"Team Plasma — Nimbasa City (Ferris Wheel)", badge:null, specialType:"mixed", category:"villain",
          team:[{name:"purrloin",level:22},{name:"joltik",level:22},{name:"sigilyph",level:23},{name:"sandile",level:22}]},
        {id:"n-bw2v",   name:"N",         role:"Team Plasma — Relic Castle",  badge:null, specialType:"mixed",   category:"villain",
          team:[{name:"sandslash",level:28},{name:"darmanitan",level:28},{name:"krokorok",level:30},{name:"carracosta",level:28},{name:"archeops",level:32}]},
        {id:"n-final",  name:"N",         role:"Team Plasma — N's Castle (Final)",badge:null,specialType:"dragon",category:"villain",
          team:[{name:"zekrom",level:52},{name:"vanilluxe",level:50},{name:"klinklang",level:50},{name:"carracosta",level:50},{name:"archeops",level:50},{name:"zoroark",level:50}]},
        {id:"ghetsis-bw",name:"Ghetsis",  role:"Team Plasma Leader — N's Castle", badge:null, specialType:"mixed", category:"villain",
          team:[{name:"cofagrigus",level:52},{name:"bouffalant",level:52},{name:"seismitoad",level:52},{name:"bisharp",level:52},{name:"eelektross",level:52},{name:"hydreigon",level:54}]},
      ]
    }
  },

  6: {
    name:"Generation VI", region:"Kalos",
    games:[{id:"xy",name:"X / Y"}],
    opponents:{
      xy:[
        {id:"viola",    name:"Viola",     role:"Gym Leader #1",  badge:"Bug Badge",     specialType:"bug",      category:"gym",
          team:[{name:"surskit",level:10},{name:"vivillon",level:12}]},
        {id:"grant",    name:"Grant",     role:"Gym Leader #2",  badge:"Cliff Badge",   specialType:"rock",     category:"gym",
          team:[{name:"amaura",level:25},{name:"tyrunt",level:25}]},
        {id:"korrina",  name:"Korrina",   role:"Gym Leader #3",  badge:"Rumble Badge",  specialType:"fighting", category:"gym",
          team:[{name:"mienfoo",level:28},{name:"machoke",level:29},{name:"lucario",level:32}]},
        {id:"ramos",    name:"Ramos",     role:"Gym Leader #4",  badge:"Plant Badge",   specialType:"grass",    category:"gym",
          team:[{name:"jumpluff",level:30},{name:"weepinbell",level:31},{name:"gogoat",level:34}]},
        {id:"clemont",  name:"Clemont",   role:"Gym Leader #5",  badge:"Voltage Badge", specialType:"electric", category:"gym",
          team:[{name:"emolga",level:35},{name:"magneton",level:35},{name:"heliolisk",level:37}]},
        {id:"valerie",  name:"Valerie",   role:"Gym Leader #6",  badge:"Fairy Badge",   specialType:"fairy",    category:"gym",
          team:[{name:"mawile",level:38},{name:"mr-mime",level:39},{name:"sylveon",level:42}]},
        {id:"olympia",  name:"Olympia",   role:"Gym Leader #7",  badge:"Psychic Badge", specialType:"psychic",  category:"gym",
          team:[{name:"sigilyph",level:44},{name:"slowking",level:45},{name:"meowstic",level:46}]},
        {id:"wulfric",  name:"Wulfric",   role:"Gym Leader #8",  badge:"Iceberg Badge", specialType:"ice",      category:"gym",
          team:[{name:"bergmite",level:46},{name:"cryogonal",level:46},{name:"avalugg",level:48}]},
        {id:"malva",    name:"Malva",     role:"Elite Four #1",  badge:null,            specialType:"fire",     category:"elite4",
          team:[{name:"pyroar",level:48},{name:"torkoal",level:48},{name:"chandelure",level:48},{name:"talonflame",level:50}]},
        {id:"siebold",  name:"Siebold",   role:"Elite Four #2",  badge:null,            specialType:"water",    category:"elite4",
          team:[{name:"clawitzer",level:52},{name:"starmie",level:48},{name:"gyarados",level:50},{name:"barbaracle",level:52}]},
        {id:"wikstrom", name:"Wikstrom",  role:"Elite Four #3",  badge:null,            specialType:"steel",    category:"elite4",
          team:[{name:"klefki",level:52},{name:"probopass",level:48},{name:"scizor",level:51},{name:"aegislash",level:52}]},
        {id:"drasna",   name:"Drasna",    role:"Elite Four #4",  badge:null,            specialType:"dragon",   category:"elite4",
          team:[{name:"dragalge",level:48},{name:"druddigon",level:49},{name:"altaria",level:49},{name:"noivern",level:51}]},
        {id:"diantha",  name:"Diantha",   role:"Champion",       badge:null,            specialType:"fairy",    category:"champion",
          team:[{name:"hawlucha",level:54},{name:"tyrantrum",level:55},{name:"aurorus",level:55},{name:"gourgeist",level:55},{name:"goodra",level:57},{name:"gardevoir",level:64}]},
        // Rivals
        {id:"serena-r1",name:"Serena",    role:"Rival — Route 4",           badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"froakie",level:9},{name:"fletchling",level:7}]},
        {id:"serena-r2",name:"Serena",    role:"Rival — Shalour City",      badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"frogadier",level:24},{name:"fletchinder",level:25},{name:"meowstic",level:25},{name:"absol",level:25}]},
        {id:"serena-r3",name:"Serena",    role:"Rival — Anistar City",      badge:null, specialType:"mixed",   category:"rival",
          team:[{name:"greninja",level:39},{name:"meowstic",level:37},{name:"absol",level:37},{name:"altaria",level:38},{name:"hawlucha",level:37}]},
        // Villains
        {id:"lysandre1",name:"Lysandre",  role:"Team Flare Leader — Lysandre Café", badge:null, specialType:"fire", category:"villain",
          team:[{name:"mienfoo",level:37},{name:"murkrow",level:37},{name:"gyarados",level:39}]},
        {id:"lysandre2",name:"Lysandre",  role:"Team Flare Leader — Lysandre Labs", badge:null, specialType:"fire", category:"villain",
          team:[{name:"mienshao",level:45},{name:"honchkrow",level:45},{name:"gyarados",level:49}]},
        {id:"lysandre3",name:"Lysandre",  role:"Team Flare Leader — Final Battle",  badge:null, specialType:"fire", category:"villain",
          team:[{name:"pyroar",level:49},{name:"mienshao",level:51},{name:"honchkrow",level:51},{name:"gyarados",level:53}]},
      ]
    }
  },

  7: {
    name:"Generation VII", region:"Alola",
    games:[{id:"sm",name:"Sun / Moon"},{id:"usum",name:"Ultra Sun / Ultra Moon"}],
    opponents:{
      sm:[
        {id:"hala",     name:"Hala",      role:"Island Kahuna (Melemele)", badge:"Fightinium Z", specialType:"fighting", category:"gym",
          team:[{name:"mankey",level:14},{name:"crabrawler",level:14},{name:"hariyama",level:17}]},
        {id:"olivia7",  name:"Olivia",    role:"Island Kahuna (Akala)",   badge:"Rockinium Z",  specialType:"rock",     category:"gym",
          team:[{name:"nosepass",level:26},{name:"boldore",level:26},{name:"lycanroc",level:27}]},
        {id:"nanu",     name:"Nanu",      role:"Island Kahuna (Ula'ula)", badge:"Darkinium Z",  specialType:"dark",     category:"gym",
          team:[{name:"sableye",level:42},{name:"krokorok",level:43},{name:"persian",level:45}]},
        {id:"hapu",     name:"Hapu",      role:"Island Kahuna (Poni)",    badge:"Groundium Z",  specialType:"ground",   category:"gym",
          team:[{name:"gastrodon",level:51},{name:"flygon",level:51},{name:"dugtrio",level:52},{name:"mudsdale",level:53}]},
        {id:"hala-e4",  name:"Hala",      role:"Elite Four #1",           badge:null,           specialType:"fighting", category:"elite4",
          team:[{name:"crabominable",level:54},{name:"hariyama",level:54},{name:"primeape",level:54},{name:"poliwrath",level:54},{name:"bewear",level:56}]},
        {id:"olivia-e4",name:"Olivia",    role:"Elite Four #2",           badge:null,           specialType:"rock",     category:"elite4",
          team:[{name:"armaldo",level:54},{name:"probopass",level:54},{name:"relicanth",level:54},{name:"carbink",level:54},{name:"lycanroc",level:56}]},
        {id:"acerola",  name:"Acerola",   role:"Elite Four #3",           badge:null,           specialType:"ghost",    category:"elite4",
          team:[{name:"drifblim",level:54},{name:"dhelmise",level:54},{name:"froslass",level:54},{name:"palossand",level:54},{name:"mimikyu",level:56}]},
        {id:"kahili",   name:"Kahili",    role:"Elite Four #4",           badge:null,           specialType:"flying",   category:"elite4",
          team:[{name:"skarmory",level:54},{name:"crobat",level:54},{name:"mandibuzz",level:54},{name:"oricorio",level:54},{name:"toucannon",level:56}]},
        {id:"kukui",    name:"Professor Kukui",role:"Champion",           badge:null,           specialType:"mixed",    category:"champion",
          team:[{name:"lycanroc",level:57},{name:"braviary",level:58},{name:"magnezone",level:58},{name:"snorlax",level:58},{name:"ninetales",level:58},{name:"incineroar",level:60}]},
        // Rivals
        {id:"hau-r1",   name:"Hau",       role:"Rival — Melemele Sea",    badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"raichu",level:19},{name:"pikachu",level:17},{name:"litten",level:18}]},
        {id:"hau-r2",   name:"Hau",       role:"Rival — Vast Poni Canyon",badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"raichu",level:43},{name:"komala",level:43},{name:"tauros",level:42},{name:"incineroar",level:44}]},
        {id:"hau-r3",   name:"Hau",       role:"Rival — Pokémon League",  badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"raichu",level:55},{name:"komala",level:53},{name:"crabominable",level:53},{name:"tauros",level:53},{name:"incineroar",level:56}]},
        // Villains
        {id:"plumeria1",name:"Plumeria",  role:"Team Skull Admin — Memorial Hill",  badge:null, specialType:"poison", category:"villain",
          team:[{name:"golbat",level:33},{name:"salazzle",level:35}]},
        {id:"plumeria2",name:"Plumeria",  role:"Team Skull Admin — Aether Paradise",badge:null, specialType:"poison", category:"villain",
          team:[{name:"toxapex",level:36},{name:"salazzle",level:38}]},
        {id:"guzma1",   name:"Guzma",     role:"Team Skull Boss — Shady House",     badge:null, specialType:"bug",    category:"villain",
          team:[{name:"golisopod",level:41},{name:"vikavolt",level:41}]},
        {id:"guzma2",   name:"Guzma",     role:"Team Skull Boss — Aether Paradise", badge:null, specialType:"bug",    category:"villain",
          team:[{name:"golisopod",level:49},{name:"masquerain",level:47},{name:"pinsir",level:47}]},
        {id:"lusamine1",name:"Lusamine",  role:"Aether Foundation — Aether Paradise",badge:null,specialType:"mixed",  category:"villain",
          team:[{name:"clefable",level:41},{name:"lilligant",level:41},{name:"mismagius",level:41},{name:"milotic",level:41},{name:"bewear",level:41}]},
      ],
      usum:[
        {id:"hala-u",   name:"Hala",      role:"Island Kahuna (Melemele)", badge:"Fightinium Z", specialType:"fighting", category:"gym",
          team:[{name:"mankey",level:14},{name:"crabrawler",level:14},{name:"hariyama",level:17}]},
        {id:"olivia-u", name:"Olivia",    role:"Island Kahuna (Akala)",   badge:"Rockinium Z",  specialType:"rock",     category:"gym",
          team:[{name:"nosepass",level:26},{name:"boldore",level:26},{name:"lycanroc",level:27}]},
        {id:"nanu-u",   name:"Nanu",      role:"Island Kahuna (Ula'ula)", badge:"Darkinium Z",  specialType:"dark",     category:"gym",
          team:[{name:"sableye",level:42},{name:"krokorok",level:43},{name:"persian",level:45}]},
        {id:"hapu-u",   name:"Hapu",      role:"Island Kahuna (Poni)",    badge:"Groundium Z",  specialType:"ground",   category:"gym",
          team:[{name:"gastrodon",level:51},{name:"flygon",level:51},{name:"dugtrio",level:52},{name:"mudsdale",level:53}]},
        {id:"hala-e4-u",name:"Hala",      role:"Elite Four #1",           badge:null,           specialType:"fighting", category:"elite4",
          team:[{name:"crabominable",level:54},{name:"hariyama",level:54},{name:"primeape",level:54},{name:"poliwrath",level:54},{name:"bewear",level:56}]},
        {id:"olivia-e4-u",name:"Olivia",  role:"Elite Four #2",           badge:null,           specialType:"rock",     category:"elite4",
          team:[{name:"armaldo",level:54},{name:"probopass",level:54},{name:"relicanth",level:54},{name:"carbink",level:54},{name:"lycanroc",level:56}]},
        {id:"acerola-u",name:"Acerola",   role:"Elite Four #3",           badge:null,           specialType:"ghost",    category:"elite4",
          team:[{name:"drifblim",level:54},{name:"dhelmise",level:54},{name:"froslass",level:54},{name:"palossand",level:54},{name:"mimikyu",level:56}]},
        {id:"kahili-u", name:"Kahili",    role:"Elite Four #4",           badge:null,           specialType:"flying",   category:"elite4",
          team:[{name:"skarmory",level:54},{name:"crobat",level:54},{name:"mandibuzz",level:54},{name:"oricorio",level:54},{name:"toucannon",level:56}]},
        {id:"kukui-u",  name:"Professor Kukui",role:"Champion",           badge:null,           specialType:"mixed",    category:"champion",
          team:[{name:"lycanroc",level:58},{name:"braviary",level:59},{name:"magnezone",level:59},{name:"snorlax",level:59},{name:"ninetales",level:59},{name:"incineroar",level:61}]},
        {id:"hau-r1-u", name:"Hau",       role:"Rival — Melemele Sea",    badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"raichu",level:19},{name:"pikachu",level:17},{name:"litten",level:18}]},
        {id:"hau-r2-u", name:"Hau",       role:"Rival — Vast Poni Canyon",badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"raichu",level:43},{name:"komala",level:43},{name:"tauros",level:42},{name:"incineroar",level:44}]},
        {id:"hau-r3-u", name:"Hau",       role:"Rival — Pokémon League",  badge:null, specialType:"mixed",    category:"rival",
          team:[{name:"raichu",level:55},{name:"komala",level:53},{name:"crabominable",level:53},{name:"tauros",level:53},{name:"incineroar",level:56}]},
        {id:"plumeria1-u",name:"Plumeria",role:"Team Skull Admin",        badge:null, specialType:"poison",   category:"villain",
          team:[{name:"golbat",level:33},{name:"salazzle",level:35}]},
        {id:"guzma1-u", name:"Guzma",     role:"Team Skull Boss — Shady House",     badge:null, specialType:"bug", category:"villain",
          team:[{name:"golisopod",level:41},{name:"vikavolt",level:41}]},
        {id:"guzma2-u", name:"Guzma",     role:"Team Skull Boss — Ultra Space",     badge:null, specialType:"bug", category:"villain",
          team:[{name:"golisopod",level:53},{name:"masquerain",level:51},{name:"vikavolt",level:53},{name:"pinsir",level:51}]},
        {id:"lusamine-u",name:"Lusamine", role:"Aether Foundation — Battle",        badge:null, specialType:"mixed", category:"villain",
          team:[{name:"bewear",level:41},{name:"clefable",level:41},{name:"mismagius",level:41},{name:"lilligant",level:41},{name:"absol",level:41},{name:"milotic",level:41}]},
      ]
    }
  },

  8: {
    name:"Generation VIII", region:"Galar",
    games:[{id:"swsh",name:"Sword / Shield"}],
    opponents:{
      swsh:[
        {id:"milo",     name:"Milo",      role:"Gym Leader #1",  badge:"Grass Badge",   specialType:"grass",    category:"gym",
          team:[{name:"gossifleur",level:19},{name:"eldegoss",level:20}]},
        {id:"nessa",    name:"Nessa",     role:"Gym Leader #2",  badge:"Water Badge",   specialType:"water",    category:"gym",
          team:[{name:"goldeen",level:22},{name:"arrokuda",level:23},{name:"drednaw",level:24}]},
        {id:"kabu",     name:"Kabu",      role:"Gym Leader #3",  badge:"Fire Badge",    specialType:"fire",     category:"gym",
          team:[{name:"ninetales",level:25},{name:"arcanine",level:25},{name:"centiskorch",level:27}]},
        {id:"bea",      name:"Bea",       role:"Gym Leader #4 (Sword)", badge:"Fighting Badge", specialType:"fighting", category:"gym",
          team:[{name:"hitmontop",level:34},{name:"pangoro",level:34},{name:"sirfetchd",level:35},{name:"machamp",level:36}]},
        {id:"allister", name:"Allister",  role:"Gym Leader #4 (Shield)",badge:"Ghost Badge",    specialType:"ghost",    category:"gym",
          team:[{name:"yamask",level:34},{name:"mimikyu",level:34},{name:"cursola",level:35},{name:"gengar",level:36}]},
        {id:"opal",     name:"Opal",      role:"Gym Leader #5",  badge:"Fairy Badge",   specialType:"fairy",    category:"gym",
          team:[{name:"weezing",level:36},{name:"mawile",level:36},{name:"togekiss",level:37},{name:"alcremie",level:38}]},
        {id:"gordie",   name:"Gordie",    role:"Gym Leader #6 (Sword)", badge:"Rock Badge",     specialType:"rock",     category:"gym",
          team:[{name:"barbaracle",level:40},{name:"shuckle",level:40},{name:"stonjourner",level:41},{name:"coalossal",level:42}]},
        {id:"melony",   name:"Melony",    role:"Gym Leader #6 (Shield)",badge:"Ice Badge",      specialType:"ice",      category:"gym",
          team:[{name:"frosmoth",level:40},{name:"eiscue",level:40},{name:"darmanitan",level:41},{name:"lapras",level:42}]},
        {id:"piers",    name:"Piers",     role:"Gym Leader #7",  badge:"Dark Badge",    specialType:"dark",     category:"gym",
          team:[{name:"scrafty",level:44},{name:"malamar",level:45},{name:"skuntank",level:45},{name:"obstagoon",level:46}]},
        {id:"raihan",   name:"Raihan",    role:"Gym Leader #8",  badge:"Dragon Badge",  specialType:"dragon",   category:"gym",
          team:[{name:"flygon",level:46},{name:"sandaconda",level:46},{name:"gigalith",level:47},{name:"duraludon",level:48}]},
        {id:"leon",     name:"Leon",      role:"Champion",       badge:null,            specialType:"mixed",    category:"champion",
          team:[{name:"aegislash",level:62},{name:"haxorus",level:63},{name:"dragapult",level:64},{name:"mr-rime",level:64},{name:"seismitoad",level:64},{name:"charizard",level:65}]},
        // Rivals
        {id:"hop-r1",   name:"Hop",       role:"Rival — Turffield (after 1st gym)", badge:null, specialType:"mixed", category:"rival",
          team:[{name:"wooloo",level:19},{name:"rookidee",level:20},{name:"grookey",level:20}]},
        {id:"hop-r2",   name:"Hop",       role:"Rival — Ballonlea (mid-game)",     badge:null, specialType:"mixed", category:"rival",
          team:[{name:"wooloo",level:35},{name:"bunnelby",level:34},{name:"hitmontop",level:35},{name:"snorlax",level:34},{name:"grookey",level:38}]},
        {id:"hop-r3",   name:"Hop",       role:"Rival — Wyndon Stadium (final)",   badge:null, specialType:"mixed", category:"rival",
          team:[{name:"dubwool",level:47},{name:"snorlax",level:47},{name:"pincurchin",level:45},{name:"flygon",level:47},{name:"rillaboom",level:48}]},
        {id:"bede-r1",  name:"Bede",      role:"Rival — Hulbury (early)",          badge:null, specialType:"psychic",category:"rival",
          team:[{name:"hattena",level:28},{name:"gothita",level:27},{name:"ponyta",level:28}]},
        {id:"bede-r2",  name:"Bede",      role:"Rival — Ballonlea (post Opal)",    badge:null, specialType:"fairy", category:"rival",
          team:[{name:"hatterene",level:42},{name:"mawile",level:40},{name:"gardevoir",level:41},{name:"rapidash",level:42}]},
        {id:"marnie-r1",name:"Marnie",    role:"Rival — Spikemuth (pre-Piers)",    badge:null, specialType:"dark",  category:"rival",
          team:[{name:"morpeko",level:36},{name:"liepard",level:36},{name:"toxicroak",level:35},{name:"scrafty",level:36}]},
        {id:"marnie8",  name:"Marnie",    role:"Rival — Champion Cup",             badge:null, specialType:"dark",  category:"rival",
          team:[{name:"morpeko",level:52},{name:"liepard",level:52},{name:"toxicroak",level:53},{name:"scrafty",level:53},{name:"grimmsnarl",level:55}]},
        // Villains
        {id:"oleana",   name:"Oleana",    role:"Macro Cosmos — Rose Tower",        badge:null, specialType:"poison", category:"villain",
          team:[{name:"garbodor",level:51},{name:"tsareena",level:53},{name:"vileplume",level:53},{name:"salazzle",level:53},{name:"copperajah",level:55}]},
        {id:"rose",     name:"Chairman Rose",role:"Macro Cosmos Leader",           badge:null, specialType:"steel",  category:"villain",
          team:[{name:"perrserker",level:60},{name:"ferrothorn",level:62},{name:"escavalier",level:62},{name:"klinklang",level:62},{name:"copperajah",level:64}]},
      ]
    }
  },

  9: {
    name:"Generation IX", region:"Paldea",
    games:[{id:"sv",name:"Scarlet / Violet"}],
    opponents:{
      sv:[
        {id:"katy",     name:"Katy",      role:"Gym Leader #1",  badge:"Bug Badge",     specialType:"bug",      category:"gym",
          team:[{name:"nymble",level:14},{name:"tarountula",level:14},{name:"teddiursa",level:15}]},
        {id:"brassius", name:"Brassius",  role:"Gym Leader #2",  badge:"Grass Badge",   specialType:"grass",    category:"gym",
          team:[{name:"petilil",level:16},{name:"smoliv",level:16},{name:"sudowoodo",level:17}]},
        {id:"iono",     name:"Iono",      role:"Gym Leader #3",  badge:"Electric Badge",specialType:"electric", category:"gym",
          team:[{name:"wattrel",level:23},{name:"bellibolt",level:23},{name:"luxio",level:23},{name:"mismagius",level:24}]},
        {id:"kofu",     name:"Kofu",      role:"Gym Leader #4",  badge:"Water Badge",   specialType:"water",    category:"gym",
          team:[{name:"veluza",level:26},{name:"wugtrio",level:26},{name:"crabominable",level:27}]},
        {id:"larry9",   name:"Larry",     role:"Gym Leader #5",  badge:"Normal Badge",  specialType:"normal",   category:"gym",
          team:[{name:"komala",level:35},{name:"dudunsparce",level:36},{name:"staraptor",level:36}]},
        {id:"ryme",     name:"Ryme",      role:"Gym Leader #6",  badge:"Ghost Badge",   specialType:"ghost",    category:"gym",
          team:[{name:"greavard",level:41},{name:"sharpedo",level:41},{name:"toxtricity",level:41},{name:"mimikyu",level:42}]},
        {id:"tulip",    name:"Tulip",     role:"Gym Leader #7",  badge:"Psychic Badge", specialType:"psychic",  category:"gym",
          team:[{name:"gardevoir",level:44},{name:"espathra",level:45},{name:"farigiraf",level:44},{name:"florges",level:44}]},
        {id:"grusha",   name:"Grusha",    role:"Gym Leader #8",  badge:"Ice Badge",     specialType:"ice",      category:"gym",
          team:[{name:"frosmoth",level:47},{name:"beartic",level:47},{name:"cetitan",level:48},{name:"altaria",level:47}]},
        {id:"rika",     name:"Rika",      role:"Elite Four #1",  badge:null,            specialType:"ground",   category:"elite4",
          team:[{name:"whiscash",level:57},{name:"camerupt",level:57},{name:"donphan",level:57},{name:"dugtrio",level:57},{name:"garchomp",level:58}]},
        {id:"poppy",    name:"Poppy",     role:"Elite Four #2",  badge:null,            specialType:"steel",    category:"elite4",
          team:[{name:"copperajah",level:58},{name:"bronzong",level:58},{name:"magnezone",level:58},{name:"corviknight",level:58},{name:"tinkaton",level:59}]},
        {id:"larry9e4", name:"Larry",     role:"Elite Four #3",  badge:null,            specialType:"normal",   category:"elite4",
          team:[{name:"tropius",level:59},{name:"oricorio",level:59},{name:"altaria",level:59},{name:"staraptor",level:59},{name:"flamigo",level:60}]},
        {id:"hassel",   name:"Hassel",    role:"Elite Four #4",  badge:null,            specialType:"dragon",   category:"elite4",
          team:[{name:"noivern",level:60},{name:"dragalge",level:60},{name:"haxorus",level:61},{name:"baxcalibur",level:61},{name:"flapple",level:60}]},
        {id:"geeta",    name:"Geeta",     role:"Champion",       badge:null,            specialType:"mixed",    category:"champion",
          team:[{name:"espathra",level:61},{name:"veluza",level:61},{name:"gogoat",level:61},{name:"glimmora",level:62},{name:"avalugg",level:61},{name:"kingambit",level:62}]},
        // Rivals
        {id:"nemona-r1",name:"Nemona",    role:"Rival — South Province (early)",   badge:null, specialType:"mixed", category:"rival",
          team:[{name:"pawmo",level:10},{name:"lechonk",level:10}]},
        {id:"nemona-r2",name:"Nemona",    role:"Rival — Cascarrafa (mid-game)",    badge:null, specialType:"mixed", category:"rival",
          team:[{name:"pawmot",level:38},{name:"lycanroc",level:36},{name:"floatzel",level:35},{name:"fuecoco",level:39}]},
        {id:"nemona-r3",name:"Nemona",    role:"Rival — Academy Ace Tournament",   badge:null, specialType:"mixed", category:"rival",
          team:[{name:"lycanroc",level:66},{name:"orthworm",level:64},{name:"dudunsparce",level:64},{name:"goodra",level:65},{name:"pawmot",level:66},{name:"skeledirge",level:67}]},
        // Villains — Team Star
        {id:"giacomo",  name:"Giacomo",   role:"Team Star — Dark Crew Boss",       badge:null, specialType:"dark",    category:"villain",
          team:[{name:"pawniard",level:21},{name:"revavroom",level:21}]},
        {id:"mela",     name:"Mela",      role:"Team Star — Fire Crew Boss",       badge:null, specialType:"fire",    category:"villain",
          team:[{name:"torkoal",level:26},{name:"revavroom",level:27}]},
        {id:"atticus",  name:"Atticus",   role:"Team Star — Poison Crew Boss",     badge:null, specialType:"poison",  category:"villain",
          team:[{name:"skuntank",level:32},{name:"muk",level:32},{name:"revavroom",level:33}]},
        {id:"ortega",   name:"Ortega",    role:"Team Star — Fairy Crew Boss",      badge:null, specialType:"fairy",   category:"villain",
          team:[{name:"granbull",level:50},{name:"wigglytuff",level:50},{name:"dachsbun",level:50},{name:"revavroom",level:51}]},
        {id:"eri",      name:"Eri",       role:"Team Star — Fighting Crew Boss",   badge:null, specialType:"fighting",category:"villain",
          team:[{name:"annihilape",level:55},{name:"toxicroak",level:55},{name:"lucario",level:55},{name:"revavroom",level:56}]},
        {id:"penny",    name:"Penny",     role:"Team Star — Supreme Boss Cassiopeia",badge:null,specialType:"mixed",  category:"villain",
          team:[{name:"vaporeon",level:62},{name:"jolteon",level:62},{name:"flareon",level:62},{name:"leafeon",level:62},{name:"glaceon",level:62},{name:"sylveon",level:63}]},
        {id:"sada",     name:"AI Prof. Sada",role:"Paradox Lab — Final Battle (Scarlet)",badge:null,specialType:"mixed",category:"villain",
          team:[{name:"great-tusk",level:65},{name:"scream-tail",level:63},{name:"brute-bonnet",level:63},{name:"flutter-mane",level:64},{name:"slither-wing",level:64},{name:"roaring-moon",level:66}]},
        {id:"turo",     name:"AI Prof. Turo",role:"Paradox Lab — Final Battle (Violet)",badge:null,specialType:"mixed",category:"villain",
          team:[{name:"iron-treads",level:65},{name:"iron-bundle",level:63},{name:"iron-hands",level:63},{name:"iron-jugulis",level:64},{name:"iron-moth",level:64},{name:"iron-valiant",level:66}]},
      ]
    }
  }
};
